services:
  mysql-container:
    image: mysql:8
    container_name: mysql-containers
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppass" ]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - cipher-network
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - mysql-container
    ports:
      - "8081:8080"
    networks:
      - cipher-network

  data-masking-be:
    image: my-app
    container_name: data-masking-be
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      mysql-container:
        condition: service_healthy
    networks:
      - cipher-network

networks:
  cipher-network:
    driver: bridge

volumes:
  mysql_data: