server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

spring:
  application:
    name: AES-GCM demo
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

open-api:
  version: v1.0.0
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  show-actuator: false
  paths-to-match: /healthcheck, /api/**

encryption:
  master_key: 908c46b7b748c9a36c805d2235c8b9fd