server:
  port: ${PORT}

spring:
  application:
    name: AES_GCM_demo
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${USER}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
    open-in-view: false

logging:
  level:
    web: debug

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  show-actuator: true
  paths-to-match: /api/**

encryption:
  master_key: ${MASTER_KEY}